/* =========================================================
   Stable Stars - La Academia de Miranda
   Datos de contenido: 23 jornadas (lun-vie), julio 2026
   Cada jornada está calibrada para ~1.5 horas de trabajo real.
   ========================================================= */

// Metadatos de semanas (rangos de índice dentro de DAYS, 0-based)
const WEEKS = [
  { title: "Semana 1 · Bienvenida al Rancho", range: [0, 2] },
  { title: "Semana 2 · Cuidando a mi Caballo", range: [3, 7] },
  { title: "Semana 3 · Explorando el Rancho y el Mapa", range: [8, 12] },
  { title: "Semana 4 · Entrenamiento y Deporte Ecuestre", range: [13, 17] },
  { title: "Semana 5 · Gran Concurso de Verano", range: [18, 22] },
];

// Ayuda para escribir preguntas más corto
function Q(text, options, answer, cat) {
  return { text, options, answer, cat };
}

const DAYS = [
  // ---------------- SEMANA 1 ----------------
  {
    date: "Miércoles 1 de julio", title: "Bienvenida al Rancho", subjectLabel: "Diagnóstico",
    intro: "¡Hola! Hoy Miranda llega por primera vez al rancho y elige a su caballo. Vamos a conocernos y a ver qué tanto sabemos.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Cuánto es 8 + 5?", ["12", "13", "14", "15",
      Q("¿En qué continente está Colombia?", ["América del Sur", "América Central", "África", "Europa"], "América del Sur", "soc")
    ], "13", "mate"),
      Q("¿Cuál de estas palabras es un sustantivo?", ["Caballo", "Correr", "Rápido", "Y"], "Caballo", "leng"),
      Q("¿Qué necesita todo ser vivo para sobrevivir?", ["Agua y alimento", "Solo dinero", "Solo aire", "Nada"], "Agua y alimento", "cien"),
      Q("¿Cuánto es 15 - 7?", ["6", "7", "8", "9"], "8", "mate"),
      Q("¿Cuál de estas palabras es un verbo?", ["Correr", "Caballo", "Rápido", "Establo"], "Correr", "leng"),
      Q("¿Qué necesitan las plantas para vivir?", ["Agua y luz del sol", "Solo tierra", "Nada", "Solo aire"], "Agua y luz del sol", "cien"),
    ],
    englishVocab: [
      { w: "Hello", es: "Hola", e: "👋" },
      { w: "Horse", es: "Caballo", e: "🐴" },
      { w: "Name", es: "Nombre", e: "🏷️" },
      { w: "Stable", es: "Establo", e: "🏠" },
      { w: "Please", es: "Por favor", e: "🙏" },
      { w: "Thank you", es: "Gracias", e: "💐" },
      { w: "Friend", es: "Amigo(a)", e: "🤝" },
      { w: "Welcome", es: "Bienvenida(o)", e: "🎉" },
    ],
    frenchVocab: [
      { w: "Bonjour", es: "Hola", e: "👋" },
      { w: "Cheval", es: "Caballo", e: "🐴" },
      { w: "Je m'appelle", es: "Me llamo", e: "🏷️" },
      { w: "Écurie", es: "Establo", e: "🏠" },
      { w: "S'il te plaît", es: "Por favor", e: "🙏" },
      { w: "Merci", es: "Gracias", e: "💐" },
      { w: "Ami(e)", es: "Amigo(a)", e: "🤝" },
      { w: "Bienvenue", es: "Bienvenida(o)", e: "🎉" },
    ],
    englishDialogue: [
      { t: "Hello! What's your name?", es: "¡Hola! ¿Cómo te llamas?" },
      { t: "My name is Miranda.", es: "Me llamo Miranda." },
      { t: "I have a horse!", es: "¡Tengo un caballo!" },
      { t: "Thank you for showing me the ranch!", es: "¡Gracias por mostrarme el rancho!" },
      { t: "You're welcome, friend!", es: "¡De nada, amiga!" },
    ],
    frenchDialogue: [
      { t: "Bonjour! Comment tu t'appelles?", es: "¡Hola! ¿Cómo te llamas?" },
      { t: "Je m'appelle Miranda.", es: "Me llamo Miranda." },
      { t: "J'ai un cheval!", es: "¡Tengo un caballo!" },
      { t: "Merci de me montrer l'écurie!", es: "¡Gracias por mostrarme el establo!" },
      { t: "De rien, mon amie!", es: "¡De nada, amiga!" },
    ],
    journalPrompt: "Dibuja (o describe con palabras) cómo se ve tu caballo. ¿Qué nombre le pusiste y por qué? Escribe al menos 5 líneas.",
  },
  {
    date: "Jueves 2 de julio", title: "Lo que necesita un caballo", subjectLabel: "Ciencias Naturales",
    intro: "Antes de montar, hay que aprender a cuidar. Descubramos qué necesita un caballo para estar sano.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Cuál de estos NO es una necesidad básica de los seres vivos?", ["Agua", "Alimento", "Aire", "Un teléfono"], "Un teléfono", "cien"),
      Q("El caballo es un animal...", ["Herbívoro", "Carnívoro", "Omnívoro", "Ninguno"], "Herbívoro", "cien"),
      Q("¿Qué le da energía al caballo para trabajar?", ["El alimento", "La música", "Los libros", "El silencio"], "El alimento", "cien"),
      Q("¿Cada cuánto debe tomar agua limpia un caballo?", ["Varias veces al día", "Una vez al mes", "Nunca", "Solo si llueve"], "Varias veces al día", "cien"),
      Q("¿Por qué es importante que el establo esté limpio?", ["Para evitar enfermedades", "Para que se vea bonito nada más", "No es importante", "Para que haga más calor"], "Para evitar enfermedades", "cien"),
      Q("¿Qué parte del cuerpo usa el caballo para masticar el heno?", ["Los dientes", "Las orejas", "La cola", "Los cascos"], "Los dientes", "cien"),
    ],
    englishVocab: [
      { w: "Hay", es: "Heno", e: "🌾" },
      { w: "Water", es: "Agua", e: "💧" },
      { w: "Feed", es: "Alimentar", e: "🥕" },
      { w: "Brush", es: "Cepillo", e: "🧹" },
      { w: "Clean", es: "Limpio", e: "🧼" },
      { w: "Healthy", es: "Sano", e: "💪" },
      { w: "Grass", es: "Pasto", e: "🌱" },
      { w: "Bucket", es: "Balde", e: "🪣" },
    ],
    frenchVocab: [
      { w: "Foin", es: "Heno", e: "🌾" },
      { w: "Eau", es: "Agua", e: "💧" },
      { w: "Nourrir", es: "Alimentar", e: "🥕" },
      { w: "Brosse", es: "Cepillo", e: "🧹" },
      { w: "Propre", es: "Limpio", e: "🧼" },
      { w: "En bonne santé", es: "Sano", e: "💪" },
      { w: "Herbe", es: "Pasto", e: "🌱" },
      { w: "Seau", es: "Balde", e: "🪣" },
    ],
    englishDialogue: [
      { t: "Is the horse hungry?", es: "¿El caballo tiene hambre?" },
      { t: "Yes! Let's feed him hay and water.", es: "¡Sí! Démosle heno y agua." },
      { t: "Let's clean his bucket too.", es: "Limpiemos también su balde." },
      { t: "Good, now he is healthy and happy.", es: "Bien, ahora está sano y feliz." },
    ],
    frenchDialogue: [
      { t: "Le cheval a faim?", es: "¿El caballo tiene hambre?" },
      { t: "Oui! Donnons-lui du foin et de l'eau.", es: "¡Sí! Démosle heno y agua." },
      { t: "Nettoyons aussi son seau.", es: "Limpiemos también su balde." },
      { t: "Bien, maintenant il est en bonne santé.", es: "Bien, ahora está sano." },
    ],
    journalPrompt: "Escribe 5 cosas que necesita tu caballo cada día para estar sano y feliz, y explica por qué cada una es importante.",
  },
  {
    date: "Viernes 3 de julio", title: "Concurso de Bienvenida", subjectLabel: "Repaso mixto", isShowDay: true,
    intro: "¡Primer Concurso Hípico del verano! Repasemos un poco de todo lo que hemos visto esta semana.",
    subjectQuestions: [
      Q("Si el sol sale por el este, ¿por dónde se oculta?", ["Oeste", "Norte", "Sur", "Centro",
      Q("¿Cuál es la capital de Colombia?", ["Medellín", "Bogotá", "Cali", "Barranquilla"], "Bogotá", "soc")
    ], "Oeste", "soc"),
      Q("12 - 5 = ?", ["5", "6", "7", "8"], "7", "mate"),
      Q("¿Cuál es el sinónimo de 'rápido'?", ["Veloz", "Lento", "Triste", "Grande"], "Veloz", "leng"),
      Q("¿Cuánto es 6 x 3?", ["16", "18", "20", "9"], "18", "mate"),
      Q("¿Cuál es el antónimo de 'grande'?", ["Pequeño", "Alto", "Fuerte", "Bonito"], "Pequeño", "leng"),
      Q("¿Qué instrumento usamos para ubicarnos en un mapa?", ["La brújula", "El termómetro", "La balanza", "El reloj"], "La brújula", "soc"),
    ],
    englishVocab: [
      { w: "North", es: "Norte", e: "⬆️" },
      { w: "South", es: "Sur", e: "⬇️" },
      { w: "East", es: "Este", e: "➡️" },
      { w: "West", es: "Oeste", e: "⬅️" },
      { w: "Map", es: "Mapa", e: "🗺️" },
      { w: "Sun", es: "Sol", e: "☀️" },
      { w: "Ranch", es: "Rancho", e: "🏡" },
      { w: "Fence", es: "Cerca", e: "🚧" },
    ],
    frenchVocab: [
      { w: "Nord", es: "Norte", e: "⬆️" },
      { w: "Sud", es: "Sur", e: "⬇️" },
      { w: "Est", es: "Este", e: "➡️" },
      { w: "Ouest", es: "Oeste", e: "⬅️" },
      { w: "Carte", es: "Mapa", e: "🗺️" },
      { w: "Soleil", es: "Sol", e: "☀️" },
      { w: "Ranch", es: "Rancho", e: "🏡" },
      { w: "Clôture", es: "Cerca", e: "🚧" },
    ],
    englishDialogue: [
      { t: "Where is the barn?", es: "¿Dónde está el establo?" },
      { t: "It's to the north, near the river.", es: "Está al norte, cerca del río." },
      { t: "The sun is shining today!", es: "¡El sol brilla hoy!" },
      { t: "Perfect day for our first ride.", es: "Día perfecto para nuestro primer paseo." },
    ],
    frenchDialogue: [
      { t: "Où est l'écurie?", es: "¿Dónde está el establo?" },
      { t: "Elle est au nord, près de la rivière.", es: "Está al norte, cerca del río." },
      { t: "Le soleil brille aujourd'hui!", es: "¡El sol brilla hoy!" },
      { t: "Jour parfait pour notre première balade.", es: "Día perfecto para nuestro primer paseo." },
    ],
    journalPrompt: "Cuenta cómo fue tu primera semana en el rancho. ¿Qué fue lo que más te gustó? Escribe al menos 5 líneas.",
  },

  // ---------------- SEMANA 2 ----------------
  {
    date: "Lunes 6 de julio", title: "Raciones para mis caballos", subjectLabel: "Matemáticas",
    intro: "Hoy toca calcular cuánta comida y agua necesitan los caballos del establo.",
    isShowDay: false,
    subjectQuestions: [
      Q("Un caballo come 3 kg de heno. ¿Cuánto heno necesitan 3 caballos?", ["6 kg", "9 kg", "12 kg", "3 kg"], "9 kg", "mate"),
      Q("Cada caballo bebe 25 litros de agua. ¿Cuántos litros beben 2 caballos?", ["25", "50", "75", "100"], "50", "mate"),
      Q("¿Cuánto es 15 + 8?", ["21", "22", "23", "24"], "23", "mate"),
      Q("Si cada caballo come 3 kg de heno y tienes 4 caballos, ¿cuánto heno necesitas?", ["9 kg", "12 kg", "15 kg", "10 kg"], "12 kg", "mate"),
      Q("Un saco de alimento pesa 20 kg. Si usas 5 kg al día, ¿para cuántos días alcanza?", ["2", "3", "4", "5"], "4", "mate"),
      Q("¿Cuánto es 40 ÷ 5?", ["6", "7", "8", "9"], "8", "mate"),
    ],
    englishVocab: [
      { w: "How much", es: "Cuánto", e: "❓" },
      { w: "How many", es: "Cuántos", e: "🔢" },
      { w: "Ten", es: "Diez", e: "🔟" },
      { w: "Twenty", es: "Veinte", e: "2️⃣0️⃣" },
      { w: "Bag", es: "Saco/Bolsa", e: "🛍️" },
      { w: "Weigh", es: "Pesar", e: "⚖️" },
      { w: "Enough", es: "Suficiente", e: "👍" },
      { w: "Every day", es: "Todos los días", e: "📆" },
    ],
    frenchVocab: [
      { w: "Combien", es: "Cuánto", e: "❓" },
      { w: "Dix", es: "Diez", e: "🔟" },
      { w: "Vingt", es: "Veinte", e: "2️⃣0️⃣" },
      { w: "Litre", es: "Litro", e: "🧴" },
      { w: "Sac", es: "Saco/Bolsa", e: "🛍️" },
      { w: "Peser", es: "Pesar", e: "⚖️" },
      { w: "Assez", es: "Suficiente", e: "👍" },
      { w: "Chaque jour", es: "Todos los días", e: "📆" },
    ],
    englishDialogue: [
      { t: "How much hay does the horse need?", es: "¿Cuánto heno necesita el caballo?" },
      { t: "It needs three kilograms.", es: "Necesita tres kilogramos." },
      { t: "Is this enough hay for today?", es: "¿Es suficiente heno para hoy?" },
      { t: "Yes, exactly enough!", es: "¡Sí, justo suficiente!" },
    ],
    frenchDialogue: [
      { t: "Combien de foin le cheval a-t-il besoin?", es: "¿Cuánto heno necesita el caballo?" },
      { t: "Il a besoin de trois kilos.", es: "Necesita tres kilos." },
      { t: "Est-ce assez de foin pour aujourd'hui?", es: "¿Es suficiente heno para hoy?" },
      { t: "Oui, juste assez!", es: "¡Sí, justo suficiente!" },
    ],
    journalPrompt: "Si tuvieras 4 caballos, ¿cuánta comida y agua necesitarías cada día? Explica cómo lo calculaste, paso a paso.",
  },
  {
    date: "Martes 7 de julio", title: "Cómo cepillar a un caballo", subjectLabel: "Lenguaje",
    intro: "Vamos a escribir instrucciones, como las que usa el mozo de cuadra cada mañana.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Cuál es el primer paso para cepillar un caballo?", ["Quitar el polvo del pelaje", "Darle de comer", "Ensillarlo", "Bañarlo con jabón",
      Q("¿Cuántos océanos rodean América del Sur?", ["1", "2", "3", "4"], "2", "soc")
    ], "Quitar el polvo del pelaje", "leng"),
      Q("Un texto instructivo sirve para...", ["Explicar cómo hacer algo paso a paso", "Contar un cuento", "Describir un paisaje", "Expresar sentimientos"], "Explicar cómo hacer algo paso a paso", "leng"),
      Q("¿Qué tipo de verbo se usa en instrucciones como 'Cepilla, moja, seca'?", ["Verbos en imperativo", "Verbos en pasado", "Adjetivos", "Sustantivos"], "Verbos en imperativo", "leng"),
      Q("¿Cuál palabra indica el último paso de una instrucción?", ["Finalmente", "Primero", "Nunca", "Ayer"], "Finalmente", "leng"),
      Q("En un texto instructivo, ¿qué se usa para organizar los pasos?", ["Números o viñetas", "Rimas", "Colores solamente", "Nada"], "Números o viñetas", "leng"),
      Q("¿Cuál de estas es una instrucción bien escrita?", ["Cepilla el pelaje con cuidado", "El pelaje cepillar cuidado con", "Cepillando quizás pelaje", "Pelaje bonito muy"], "Cepilla el pelaje con cuidado", "leng"),
    ],
    englishVocab: [
      { w: "Brush", es: "Cepilla", e: "🧹" },
      { w: "Comb", es: "Peina", e: "💇" },
      { w: "Clean", es: "Limpia", e: "🧼" },
      { w: "Feed", es: "Alimenta", e: "🥕" },
      { w: "Careful", es: "Con cuidado", e: "🤲" },
      { w: "Gently", es: "Suavemente", e: "🌸" },
      { w: "Step", es: "Paso", e: "👣" },
      { w: "Finish", es: "Terminar", e: "🏁" },
    ],
    frenchVocab: [
      { w: "Brosse", es: "Cepilla", e: "🧹" },
      { w: "Peigne", es: "Peina", e: "💇" },
      { w: "Nettoie", es: "Limpia", e: "🧼" },
      { w: "Nourris", es: "Alimenta", e: "🥕" },
      { w: "Avec soin", es: "Con cuidado", e: "🤲" },
      { w: "Doucement", es: "Suavemente", e: "🌸" },
      { w: "Étape", es: "Paso", e: "👣" },
      { w: "Finir", es: "Terminar", e: "🏁" },
    ],
    englishDialogue: [
      { t: "Brush the mane, please.", es: "Cepilla la crin, por favor." },
      { t: "Okay! I will comb it gently.", es: "¡Listo! La voy a peinar con cuidado." },
      { t: "What is the next step?", es: "¿Cuál es el siguiente paso?" },
      { t: "Now we finish gently.", es: "Ahora terminamos con suavidad." },
    ],
    frenchDialogue: [
      { t: "Brosse la crinière, s'il te plaît.", es: "Cepilla la crin, por favor." },
      { t: "D'accord! Je vais la peigner doucement.", es: "¡Listo! La voy a peinar con cuidado." },
      { t: "Quelle est la prochaine étape?", es: "¿Cuál es el siguiente paso?" },
      { t: "Maintenant on finit doucement.", es: "Ahora terminamos con suavidad." },
    ],
    journalPrompt: "Escribe las instrucciones completas para bañar a un caballo (mínimo 6 pasos, usando verbos como 'moja', 'frota', 'enjuaga', 'seca').",
  },
  {
    date: "Miércoles 8 de julio", title: "El cuerpo del caballo", subjectLabel: "Ciencias Naturales",
    intro: "Comparemos el cuerpo del caballo con el nuestro: huesos, músculos y movimiento.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Qué parte del cuerpo usa el caballo para caminar y correr?", ["Las patas", "Las orejas", "La cola", "Los ojos"], "Las patas", "cien"),
      Q("El casco del caballo es como... en los humanos.", ["La uña", "El cabello", "La oreja", "El diente"], "La uña", "cien"),
      Q("¿Para qué le sirve la cola al caballo?", ["Espantar insectos y mantener el equilibrio", "Para comer", "Para escuchar", "Para ver"], "Espantar insectos y mantener el equilibrio", "cien"),
      Q("¿Cómo se llama el conjunto de huesos del cuerpo?", ["Esqueleto", "Músculo", "Piel", "Sangre"], "Esqueleto", "cien"),
      Q("¿Qué función cumplen los músculos?", ["Permiten el movimiento", "Solo dan color", "No sirven para nada", "Sirven para respirar únicamente"], "Permiten el movimiento", "cien"),
      Q("¿Qué parte protege el cerebro del caballo?", ["El cráneo", "La cola", "Las patas", "El casco"], "El cráneo", "cien"),
    ],
    englishVocab: [
      { w: "Hoof", es: "Casco", e: "🦶" },
      { w: "Mane", es: "Crin", e: "💈" },
      { w: "Tail", es: "Cola", e: "🎏" },
      { w: "Leg", es: "Pata", e: "🦵" },
      { w: "Bone", es: "Hueso", e: "🦴" },
      { w: "Muscle", es: "Músculo", e: "💪" },
      { w: "Skin", es: "Piel", e: "🫱" },
      { w: "Ear", es: "Oreja", e: "👂" },
    ],
    frenchVocab: [
      { w: "Sabot", es: "Casco", e: "🦶" },
      { w: "Crinière", es: "Crin", e: "💈" },
      { w: "Queue", es: "Cola", e: "🎏" },
      { w: "Jambe", es: "Pata", e: "🦵" },
      { w: "Os", es: "Hueso", e: "🦴" },
      { w: "Muscle", es: "Músculo", e: "💪" },
      { w: "Peau", es: "Piel", e: "🫱" },
      { w: "Oreille", es: "Oreja", e: "👂" },
    ],
    englishDialogue: [
      { t: "Look at the horse's mane!", es: "¡Mira la crin del caballo!" },
      { t: "It's so long and shiny.", es: "Es tan larga y brillante." },
      { t: "Horses have very strong bones.", es: "Los caballos tienen huesos muy fuertes." },
      { t: "And big muscles to run fast!", es: "¡Y músculos grandes para correr rápido!" },
    ],
    frenchDialogue: [
      { t: "Regarde la crinière du cheval!", es: "¡Mira la crin del caballo!" },
      { t: "Elle est si longue et brillante.", es: "Es tan larga y brillante." },
      { t: "Les chevaux ont des os très forts.", es: "Los caballos tienen huesos muy fuertes." },
      { t: "Et de grands muscles pour courir vite!", es: "¡Y músculos grandes para correr rápido!" },
    ],
    journalPrompt: "Describe con palabras el cuerpo de un caballo, nombrando al menos 6 partes en español y explicando para qué sirve cada una.",
  },
  {
    date: "Jueves 9 de julio", title: "El rancho y su gente", subjectLabel: "Ciencias Sociales",
    intro: "¿Quién trabaja en un rancho? Descubramos los oficios y la economía ganadera de Colombia.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Qué actividad económica se relaciona con la cría de caballos y ganado?", ["La ganadería", "La pesca", "La minería", "El comercio digital",
      Q("¿Qué es la línea ecuatorial?", ["Una línea imaginaria que divide la Tierra", "Una montaña", "Un río", "Una frontera"], "Una línea imaginaria que divide la Tierra", "soc")
    ], "La ganadería", "soc"),
      Q("¿Qué región de Colombia es reconocida por su tradición ganadera y de caballos de paso fino?", ["Los Llanos Orientales", "El Amazonas profundo", "La Guajira desértica", "Ninguna"], "Los Llanos Orientales", "soc"),
      Q("El trabajo de cuidar y entrenar caballos lo hace un...", ["Palafrenero (mozo de cuadra)", "Panadero", "Piloto", "Contador"], "Palafrenero (mozo de cuadra)", "soc"),
      Q("¿Qué es una economía rural?", ["La que depende del campo y la ganadería", "La que solo depende de la tecnología", "La que no existe", "La del mar únicamente"], "La que depende del campo y la ganadería", "soc"),
      Q("¿Qué producto agrícola exporta mucho Colombia?", ["Café", "Nieve", "Petróleo del desierto", "Ninguno"], "Café", "soc"),
      Q("¿Por qué es importante cuidar a los animales de trabajo?", ["Porque ayudan en las labores del campo", "No es importante", "Porque son decorativos", "Porque cuestan dinero solamente"], "Porque ayudan en las labores del campo", "soc"),
    ],
    englishVocab: [
      { w: "Farmer", es: "Granjero", e: "🧑‍🌾" },
      { w: "Groom", es: "Mozo de cuadra", e: "🧑‍🔧" },
      { w: "Vet", es: "Veterinario", e: "🩺" },
      { w: "Rider", es: "Jinete", e: "🏇" },
      { w: "Work", es: "Trabajo", e: "🔨" },
      { w: "Countryside", es: "Campo", e: "🌾" },
      { w: "Export", es: "Exportar", e: "🚢" },
      { w: "Coffee", es: "Café", e: "☕" },
    ],
    frenchVocab: [
      { w: "Fermier", es: "Granjero", e: "🧑‍🌾" },
      { w: "Palefrenier", es: "Mozo de cuadra", e: "🧑‍🔧" },
      { w: "Vétérinaire", es: "Veterinario", e: "🩺" },
      { w: "Cavalier", es: "Jinete", e: "🏇" },
      { w: "Travail", es: "Trabajo", e: "🔨" },
      { w: "Campagne", es: "Campo", e: "🌾" },
      { w: "Exporter", es: "Exportar", e: "🚢" },
      { w: "Café", es: "Café", e: "☕" },
    ],
    englishDialogue: [
      { t: "What do you want to be?", es: "¿Qué quieres ser?" },
      { t: "I want to be a horse rider!", es: "¡Quiero ser jinete!" },
      { t: "My family works in the countryside.", es: "Mi familia trabaja en el campo." },
      { t: "Colombia exports a lot of coffee!", es: "¡Colombia exporta mucho café!" },
    ],
    frenchDialogue: [
      { t: "Que veux-tu être?", es: "¿Qué quieres ser?" },
      { t: "Je veux être cavalière!", es: "¡Quiero ser jinete!" },
      { t: "Ma famille travaille à la campagne.", es: "Mi familia trabaja en el campo." },
      { t: "La Colombie exporte beaucoup de café!", es: "¡Colombia exporta mucho café!" },
    ],
    journalPrompt: "¿Qué oficio del rancho te gustaría tener? Explica por qué, y describe cómo sería un día normal de trabajo en ese oficio.",
  },
  {
    date: "Viernes 10 de julio", title: "Concurso Hípico #1", subjectLabel: "Repaso de la semana", isShowDay: true,
    intro: "¡Es viernes de concurso! Organicemos el horario completo del establo con todo lo aprendido esta semana.",
    subjectQuestions: [
      Q("El establo abre a las 6:00 am y el entrenamiento dura 2 horas. ¿A qué hora termina?", ["7:00 am", "8:00 am", "9:00 am", "6:30 am"], "8:00 am", "mate"),
      Q("Ordena: para montar primero hay que...", ["Cepillar", "Ensillar", "Montar", "Ninguna de las anteriores"], "Cepillar", "leng"),
      Q("¿Qué debe revisar el mozo de cuadra antes de montar?", ["Que la silla esté bien puesta", "Que llueva", "Que haya luna llena", "Nada"], "Que la silla esté bien puesta", "cien"),
      Q("Si el entrenamiento empieza a las 7:00 am y dura 90 minutos, ¿a qué hora termina?", ["8:00 am", "8:30 am", "9:00 am", "7:30 am"], "8:30 am", "mate"),
      Q("¿Cuál es el sinónimo de 'limpio'?", ["Aseado", "Sucio", "Roto", "Viejo"], "Aseado", "leng"),
      Q("¿Qué debemos revisar en los cascos del caballo antes de montar?", ["Que estén limpios y sin piedras", "Que tengan color bonito", "Nada", "Que sean grandes"], "Que estén limpios y sin piedras", "cien"),
    ],
    englishVocab: [
      { w: "Morning", es: "Mañana", e: "🌅" },
      { w: "Feed time", es: "Hora de comer", e: "⏰" },
      { w: "Brush", es: "Cepillar", e: "🧹" },
      { w: "Ride", es: "Montar", e: "🏇" },
      { w: "Routine", es: "Rutina", e: "🔁" },
      { w: "Check", es: "Revisar", e: "🔍" },
      { w: "Ready", es: "Listo", e: "✅" },
      { w: "Start", es: "Empezar", e: "🏁" },
    ],
    frenchVocab: [
      { w: "Matin", es: "Mañana", e: "🌅" },
      { w: "Heure du repas", es: "Hora de comer", e: "⏰" },
      { w: "Brosser", es: "Cepillar", e: "🧹" },
      { w: "Monter", es: "Montar", e: "🏇" },
      { w: "Routine", es: "Rutina", e: "🔁" },
      { w: "Vérifier", es: "Revisar", e: "🔍" },
      { w: "Prêt", es: "Listo", e: "✅" },
      { w: "Commencer", es: "Empezar", e: "🏁" },
    ],
    englishDialogue: [
      { t: "What time do we feed the horses?", es: "¿A qué hora alimentamos a los caballos?" },
      { t: "At seven in the morning!", es: "¡A las siete de la mañana!" },
      { t: "Are we ready to start?", es: "¿Estamos listos para empezar?" },
      { t: "Let's check everything first.", es: "Revisemos todo primero." },
    ],
    frenchDialogue: [
      { t: "À quelle heure nourrit-on les chevaux?", es: "¿A qué hora alimentamos a los caballos?" },
      { t: "À sept heures du matin!", es: "¡A las siete de la mañana!" },
      { t: "Sommes-nous prêts à commencer?", es: "¿Estamos listos para empezar?" },
      { t: "Vérifions tout d'abord.", es: "Revisemos todo primero." },
    ],
    journalPrompt: "Escribe el horario ideal de un día completo en el establo, desde que abre hasta que cierra.",
  },

  // ---------------- SEMANA 3 ----------------
  {
    date: "Lunes 13 de julio", title: "Construyendo el corral", subjectLabel: "Matemáticas",
    intro: "Hoy diseñamos un corral nuevo: toca calcular perímetro y área.",
    isShowDay: false,
    subjectQuestions: [
      Q("Un corral rectangular mide 5 m de largo y 3 m de ancho. ¿Cuál es su perímetro?", ["8 m", "15 m", "16 m", "10 m",
      Q("¿Cuál es el río más largo de América del Sur?", ["Río de la Plata", "Amazonas", "Orinoco", "Magdalena"], "Amazonas", "soc")
    ], "16 m", "mate"),
      Q("¿Cuál es el área de ese mismo corral (5 m x 3 m)?", ["8", "15", "16", "20"], "15", "mate"),
      Q("¿Cuántos lados tiene un corral con forma de cuadrado?", ["2", "3", "4", "5"], "4", "mate"),
      Q("Un corral cuadrado tiene lados de 4 m. ¿Cuál es su área?", ["8", "12", "16", "20"], "16", "mate"),
      Q("Si necesito 20 m de cerca y ya tengo 12 m, ¿cuántos metros me faltan?", ["6", "8", "10", "12"], "8", "mate"),
      Q("¿Cuántos lados tiene un hexágono (como algunos corrales)?", ["4", "5", "6", "7"], "6", "mate"),
    ],
    englishVocab: [
      { w: "Shape", es: "Forma", e: "🔷" },
      { w: "Square", es: "Cuadrado", e: "⬛" },
      { w: "Fence", es: "Cerca", e: "🚧" },
      { w: "Meter", es: "Metro", e: "📏" },
      { w: "Wide", es: "Ancho", e: "↔️" },
      { w: "Long", es: "Largo", e: "📐" },
      { w: "Build", es: "Construir", e: "🔨" },
      { w: "Wood", es: "Madera", e: "🪵" },
    ],
    frenchVocab: [
      { w: "Forme", es: "Forma", e: "🔷" },
      { w: "Carré", es: "Cuadrado", e: "⬛" },
      { w: "Clôture", es: "Cerca", e: "🚧" },
      { w: "Mètre", es: "Metro", e: "📏" },
      { w: "Large", es: "Ancho", e: "↔️" },
      { w: "Long", es: "Largo", e: "📐" },
      { w: "Construire", es: "Construir", e: "🔨" },
      { w: "Bois", es: "Madera", e: "🪵" },
    ],
    englishDialogue: [
      { t: "We need a new fence.", es: "Necesitamos una cerca nueva." },
      { t: "How many meters do we need?", es: "¿Cuántos metros necesitamos?" },
      { t: "How wide should the fence be?", es: "¿Qué tan ancha debe ser la cerca?" },
      { t: "Let's build it with strong wood.", es: "Construyámosla con madera fuerte." },
    ],
    frenchDialogue: [
      { t: "Nous avons besoin d'une nouvelle clôture.", es: "Necesitamos una cerca nueva." },
      { t: "Combien de mètres avons-nous besoin?", es: "¿Cuántos metros necesitamos?" },
      { t: "Quelle largeur pour la clôture?", es: "¿Qué tan ancha debe ser la cerca?" },
      { t: "Construisons-la avec du bois solide.", es: "Construyámosla con madera fuerte." },
    ],
    journalPrompt: "Diseña tu propio corral: describe su forma, sus medidas, y calcula su perímetro y su área.",
  },
  {
    date: "Martes 14 de julio", title: "El caballo y el burro (fábula)", subjectLabel: "Lenguaje",
    intro: "Leamos una fábula sobre un caballo y un burro, y busquemos su moraleja.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Qué es la moraleja de una fábula?", ["La enseñanza que deja la historia", "El título del cuento", "El nombre del autor", "La fecha"], "La enseñanza que deja la historia", "leng"),
      Q("En las fábulas, los animales generalmente...", ["Hablan y actúan como personas", "No aparecen", "Solo corren", "Vuelan"], "Hablan y actúan como personas", "leng"),
      Q("¿Cuál es un personaje típico de una fábula de caballos?", ["El caballo trabajador y el burro perezoso", "Un robot", "Un carro", "Un celular"], "El caballo trabajador y el burro perezoso", "leng"),
      Q("¿Qué es un personaje principal?", ["El que vive la historia central", "Un lugar de la historia", "El título del libro", "El autor"], "El que vive la historia central", "leng"),
      Q("¿Las fábulas casi siempre tienen...?", ["Una enseñanza o moraleja", "Solo dibujos", "Números", "Ninguna enseñanza"], "Una enseñanza o moraleja", "leng"),
      Q("¿Qué palabra podría iniciar una fábula?", ["Había una vez", "Mañana será", "Ahora mismo", "Nunca"], "Había una vez", "leng"),
    ],
    englishVocab: [
      { w: "Once upon a time", es: "Había una vez", e: "📖" },
      { w: "Story", es: "Historia", e: "📚" },
      { w: "Moral", es: "Moraleja", e: "💡" },
      { w: "Fable", es: "Fábula", e: "🦊" },
      { w: "Character", es: "Personaje", e: "🎭" },
      { w: "Lesson", es: "Enseñanza", e: "🎓" },
      { w: "Donkey", es: "Burro", e: "🫏" },
      { w: "Heavy", es: "Pesado", e: "🏋️" },
    ],
    frenchVocab: [
      { w: "Il était une fois", es: "Había una vez", e: "📖" },
      { w: "Histoire", es: "Historia", e: "📚" },
      { w: "Morale", es: "Moraleja", e: "💡" },
      { w: "Fable", es: "Fábula", e: "🦊" },
      { w: "Personnage", es: "Personaje", e: "🎭" },
      { w: "Leçon", es: "Enseñanza", e: "🎓" },
      { w: "Âne", es: "Burro", e: "🫏" },
      { w: "Lourd", es: "Pesado", e: "🏋️" },
    ],
    englishDialogue: [
      { t: "Do you know this fable?", es: "¿Conoces esta fábula?" },
      { t: "Yes, the moral is: work together!", es: "Sí, la moraleja es: ¡trabajar en equipo!" },
      { t: "Who is the main character?", es: "¿Quién es el personaje principal?" },
      { t: "The horse, and also the donkey.", es: "El caballo, y también el burro." },
    ],
    frenchDialogue: [
      { t: "Connais-tu cette fable?", es: "¿Conoces esta fábula?" },
      { t: "Oui, la morale est: travaillons ensemble!", es: "Sí, la moraleja es: ¡trabajemos juntos!" },
      { t: "Qui est le personnage principal?", es: "¿Quién es el personaje principal?" },
      { t: "Le cheval, et aussi l'âne.", es: "El caballo, y también el burro." },
    ],
    journalPrompt: "Inventa el final de esta fábula: 'Un caballo y un burro cargaban bultos muy pesados...' Escribe al menos 6 líneas e incluye una moraleja.",
  },
  {
    date: "Miércoles 15 de julio", title: "El agua del bebedero", subjectLabel: "Ciencias Naturales",
    intro: "¿De dónde viene el agua que beben los caballos? Sigamos el ciclo del agua.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Cuál es el primer paso del ciclo del agua?", ["Evaporación", "Un terremoto", "Un nevado", "Ninguno",
      Q("¿En qué siglo llegó Cristóbal Colón a América?", ["Siglo XV", "Siglo XVI", "Siglo XVII", "Siglo XVIII"], "Siglo XV", "soc")
    ], "Evaporación", "cien"),
      Q("El agua de lluvia llena los... para que beban los caballos.", ["Bebederos y ríos", "Libros", "Sillas", "Cepillos"], "Bebederos y ríos", "cien"),
      Q("¿Qué pasa cuando el agua se evapora?", ["Sube al cielo y forma nubes", "Desaparece para siempre", "Se congela", "Se vuelve tierra"], "Sube al cielo y forma nubes", "cien"),
      Q("¿Cómo se llama cuando el agua sube al cielo en forma de vapor?", ["Evaporación", "Congelación", "Fusión", "Ninguna"], "Evaporación", "cien"),
      Q("¿Cómo se llama cuando cae el agua de las nubes?", ["Precipitación (lluvia)", "Evaporación", "Sequía", "Erupción"], "Precipitación (lluvia)", "cien"),
      Q("¿Por qué es importante cuidar el agua?", ["Es un recurso limitado y necesario para la vida", "Es infinita", "No es importante", "Solo sirve para bañarse"], "Es un recurso limitado y necesario para la vida", "cien"),
    ],
    englishVocab: [
      { w: "Rain", es: "Lluvia", e: "🌧️" },
      { w: "Cloud", es: "Nube", e: "☁️" },
      { w: "River", es: "Río", e: "🏞️" },
      { w: "Water cycle", es: "Ciclo del agua", e: "🔄" },
      { w: "Steam", es: "Vapor", e: "💨" },
      { w: "Drop", es: "Gota", e: "💧" },
      { w: "Sky", es: "Cielo", e: "🌤️" },
      { w: "Important", es: "Importante", e: "❗" },
    ],
    frenchVocab: [
      { w: "Pluie", es: "Lluvia", e: "🌧️" },
      { w: "Nuage", es: "Nube", e: "☁️" },
      { w: "Rivière", es: "Río", e: "🏞️" },
      { w: "Cycle de l'eau", es: "Ciclo del agua", e: "🔄" },
      { w: "Vapeur", es: "Vapor", e: "💨" },
      { w: "Goutte", es: "Gota", e: "💧" },
      { w: "Ciel", es: "Cielo", e: "🌤️" },
      { w: "Important", es: "Importante", e: "❗" },
    ],
    englishDialogue: [
      { t: "It's raining!", es: "¡Está lloviendo!" },
      { t: "Great, the horses will have more water.", es: "Genial, los caballos tendrán más agua." },
      { t: "Look, steam rises to the sky!", es: "¡Mira, el vapor sube al cielo!" },
      { t: "Water is very important to us.", es: "El agua es muy importante para nosotros." },
    ],
    frenchDialogue: [
      { t: "Il pleut!", es: "¡Está lloviendo!" },
      { t: "Super, les chevaux auront plus d'eau.", es: "Genial, los caballos tendrán más agua." },
      { t: "Regarde, la vapeur monte au ciel!", es: "¡Mira, el vapor sube al cielo!" },
      { t: "L'eau est très importante pour nous.", es: "El agua es muy importante para nosotros." },
    ],
    journalPrompt: "Explica con tus palabras (y dibujos si quieres) cómo el agua de lluvia llega hasta el bebedero de los caballos, paso a paso.",
  },
  {
    date: "Jueves 16 de julio", title: "El mapa del rancho", subjectLabel: "Ciencias Sociales",
    intro: "Vamos a trazar rutas de cabalgata usando el mapa y los puntos cardinales.",
    isShowDay: false,
    subjectQuestions: [
      Q("Si el río está al norte del establo, ¿hacia dónde debo caminar para llegar?", ["Hacia arriba en el mapa (norte)", "Hacia abajo (sur)", "Hacia la derecha (este)", "No importa"], "Hacia arriba en el mapa (norte)", "soc"),
      Q("¿Qué instrumento nos ayuda a saber dónde queda el norte?", ["La brújula", "El termómetro", "La regla", "El reloj"], "La brújula", "soc"),
      Q("En un mapa, ¿qué representan las líneas de una ruta?", ["El camino a seguir", "Los colores del cielo", "Nada", "Los nombres de los caballos"], "El camino a seguir", "soc"),
      Q("¿Qué representan los colores en un mapa?", ["Diferentes tipos de terreno o zonas", "Nada", "Solo decoración", "El clima del día"], "Diferentes tipos de terreno o zonas", "soc"),
      Q("¿Qué es una ruta?", ["El camino que se sigue para llegar a un lugar", "Un tipo de animal", "Un instrumento musical", "Una comida"], "El camino que se sigue para llegar a un lugar", "soc"),
      Q("Si camino hacia el este y luego hacia el sur, ¿qué dirección general tomé?", ["Sureste", "Noroeste", "Norte", "Oeste"], "Sureste", "soc"),
    ],
    englishVocab: [
      { w: "Map", es: "Mapa", e: "🗺️" },
      { w: "Compass", es: "Brújula", e: "🧭" },
      { w: "North", es: "Norte", e: "⬆️" },
      { w: "River", es: "Río", e: "🏞️" },
      { w: "Direction", es: "Dirección", e: "🧭" },
      { w: "Path", es: "Camino", e: "🛤️" },
      { w: "Forest", es: "Bosque", e: "🌲" },
      { w: "Near", es: "Cerca", e: "📍" },
    ],
    frenchVocab: [
      { w: "Carte", es: "Mapa", e: "🗺️" },
      { w: "Boussole", es: "Brújula", e: "🧭" },
      { w: "Nord", es: "Norte", e: "⬆️" },
      { w: "Rivière", es: "Río", e: "🏞️" },
      { w: "Direction", es: "Dirección", e: "🧭" },
      { w: "Chemin", es: "Camino", e: "🛤️" },
      { w: "Forêt", es: "Bosque", e: "🌲" },
      { w: "Près", es: "Cerca", e: "📍" },
    ],
    englishDialogue: [
      { t: "Which way is the river?", es: "¿Hacia dónde queda el río?" },
      { t: "Go north, then turn east.", es: "Ve al norte, luego gira al este." },
      { t: "Which direction is the forest?", es: "¿En qué dirección está el bosque?" },
      { t: "It's near the river, to the north.", es: "Está cerca del río, al norte." },
    ],
    frenchDialogue: [
      { t: "Quelle direction pour la rivière?", es: "¿Hacia dónde queda el río?" },
      { t: "Va au nord, puis tourne à l'est.", es: "Ve al norte, luego gira al este." },
      { t: "Dans quelle direction est la forêt?", es: "¿En qué dirección está el bosque?" },
      { t: "Elle est près de la rivière, au nord.", es: "Está cerca del río, al norte." },
    ],
    journalPrompt: "Describe un mapa sencillo del rancho: dónde está el establo, el río, el bosque y los corrales. Usa los puntos cardinales.",
  },
  {
    date: "Viernes 17 de julio", title: "Concurso Hípico #2", subjectLabel: "Carrera de orientación", isShowDay: true,
    intro: "¡Carrera de orientación! Usa el mapa, calcula distancias y sigue las pistas.",
    subjectQuestions: [
      Q("La ruta mide 12 km y ya recorriste 7 km. ¿Cuántos km faltan?", ["4", "5", "6", "7",
      Q("¿Quiénes eran los muiscas?", ["Pueblo indígena de Colombia", "Conquistadores españoles", "Animales del rancho", "Plantas"], "Pueblo indígena de Colombia", "soc")
    ], "5", "mate"),
      Q("La pista dice 'gira a la izquierda después del río'. ¿Qué debes hacer primero?", ["Cruzar el río", "Girar", "Ambas a la vez", "Ninguna"], "Cruzar el río", "leng"),
      Q("¿Qué región de Colombia tiene llanuras ideales para cabalgar largas distancias?", ["Los Llanos Orientales", "La alta montaña nevada", "El fondo del mar", "Ninguna"], "Los Llanos Orientales", "soc"),
      Q("La ruta completa mide 20 km. Si ya llevas la mitad, ¿cuántos km has recorrido?", ["5", "10", "15", "20"], "10", "mate"),
      Q("¿Qué tipo de palabra es 'rápidamente'?", ["Adverbio", "Sustantivo", "Verbo", "Artículo"], "Adverbio", "leng"),
      Q("¿Qué debemos llevar siempre en una cabalgata larga?", ["Agua y un mapa", "Nada", "Solo dulces", "Un televisor"], "Agua y un mapa", "soc"),
    ],
    englishVocab: [
      { w: "Turn left", es: "Gira a la izquierda", e: "⬅️" },
      { w: "Turn right", es: "Gira a la derecha", e: "➡️" },
      { w: "Straight", es: "Derecho", e: "⬆️" },
      { w: "Distance", es: "Distancia", e: "📏" },
      { w: "Halfway", es: "A mitad de camino", e: "➗" },
      { w: "Finish line", es: "Meta", e: "🏁" },
      { w: "Fast", es: "Rápido", e: "⚡" },
      { w: "Slow", es: "Lento", e: "🐢" },
    ],
    frenchVocab: [
      { w: "Tourne à gauche", es: "Gira a la izquierda", e: "⬅️" },
      { w: "Tourne à droite", es: "Gira a la derecha", e: "➡️" },
      { w: "Tout droit", es: "Derecho", e: "⬆️" },
      { w: "Distance", es: "Distancia", e: "📏" },
      { w: "À mi-chemin", es: "A mitad de camino", e: "➗" },
      { w: "Ligne d'arrivée", es: "Meta", e: "🏁" },
      { w: "Rapide", es: "Rápido", e: "⚡" },
      { w: "Lent", es: "Lento", e: "🐢" },
    ],
    englishDialogue: [
      { t: "Turn left, then go straight!", es: "¡Gira a la izquierda y luego sigue derecho!" },
      { t: "Got it, I can see the finish line!", es: "¡Entendido, ya veo la meta!" },
      { t: "We are halfway there!", es: "¡Vamos a mitad de camino!" },
      { t: "The finish line is close now.", es: "La meta está cerca ahora." },
    ],
    frenchDialogue: [
      { t: "Tourne à gauche, puis va tout droit!", es: "¡Gira a la izquierda y luego sigue derecho!" },
      { t: "Compris, je vois la ligne d'arrivée!", es: "¡Entendido, ya veo la meta!" },
      { t: "Nous sommes à mi-chemin!", es: "¡Vamos a mitad de camino!" },
      { t: "La ligne d'arrivée est proche maintenant.", es: "La meta está cerca ahora." },
    ],
    journalPrompt: "Cuenta cómo te fue en la carrera de orientación de hoy: qué ruta seguiste y qué fue lo más difícil.",
  },

  // ---------------- SEMANA 4 ----------------
  {
    date: "Lunes 20 de julio", title: "El circuito de salto", subjectLabel: "Matemáticas",
    intro: "Los circuitos de salto se dividen en fracciones. Vamos a calcular el recorrido.",
    isShowDay: false,
    subjectQuestions: [
      Q("El circuito tiene 8 obstáculos. Si ya saltaste la mitad, ¿cuántos saltaste?", ["2", "4", "6", "8"], "4", "mate"),
      Q("¿Cómo se escribe 'un cuarto' en fracción?", ["1/4", "1/2", "1/3", "1/5"], "1/4", "mate"),
      Q("Si el tiempo del circuito es 45.5 segundos, ¿cuál es la parte decimal?", [".5", ".45", ".0", "5"], ".5", "mate"),
      Q("¿Cómo se escribe 'tres cuartos' en fracción?", ["3/4", "4/3", "1/4", "3/3"], "3/4", "mate"),
      Q("Si el circuito dura 60 segundos y ya pasaron 3/4, ¿cuántos segundos han pasado?", ["30", "45", "15", "60"], "45", "mate"),
      Q("¿Cuál fracción es mayor: 1/2 o 1/4?", ["1/2", "1/4", "Son iguales", "Ninguna"], "1/2", "mate"),
    ],
    englishVocab: [
      { w: "Half", es: "Mitad", e: "🌗" },
      { w: "Quarter", es: "Cuarto", e: "🍕" },
      { w: "Jump", es: "Saltar", e: "🤸" },
      { w: "Time", es: "Tiempo", e: "⏱️" },
      { w: "Course", es: "Circuito", e: "🏇" },
      { w: "Obstacle", es: "Obstáculo", e: "🚧" },
      { w: "Clear (a jump)", es: "Superar (un salto)", e: "✨" },
      { w: "Fault", es: "Falta", e: "❌" },
    ],
    frenchVocab: [
      { w: "Demi", es: "Mitad", e: "🌗" },
      { w: "Quart", es: "Cuarto", e: "🍕" },
      { w: "Saut", es: "Salto", e: "🤸" },
      { w: "Temps", es: "Tiempo", e: "⏱️" },
      { w: "Parcours", es: "Circuito", e: "🏇" },
      { w: "Obstacle", es: "Obstáculo", e: "🚧" },
      { w: "Franchir", es: "Superar", e: "✨" },
      { w: "Faute", es: "Falta", e: "❌" },
    ],
    englishDialogue: [
      { t: "How many jumps are left?", es: "¿Cuántos saltos faltan?" },
      { t: "Just half of the course!", es: "¡Solo la mitad del circuito!" },
      { t: "She clears the obstacle perfectly!", es: "¡Ella supera el obstáculo perfectamente!" },
      { t: "No faults, amazing round!", es: "¡Sin faltas, ronda increíble!" },
    ],
    frenchDialogue: [
      { t: "Combien de sauts reste-t-il?", es: "¿Cuántos saltos faltan?" },
      { t: "Juste la moitié du parcours!", es: "¡Solo la mitad del circuito!" },
      { t: "Elle franchit l'obstacle parfaitement!", es: "¡Ella supera el obstáculo perfectamente!" },
      { t: "Aucune faute, ronde incroyable!", es: "¡Sin faltas, ronda increíble!" },
    ],
    journalPrompt: "Si el circuito tiene 8 obstáculos y saltas 1/4 de ellos, ¿cuántos son? Explica tu respuesta e inventa otro ejemplo con fracciones.",
  },
  {
    date: "Martes 21 de julio", title: "Mi primera competencia", subjectLabel: "Lenguaje",
    intro: "Vamos a escribir una narración con inicio, nudo y desenlace.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Cuáles son las 3 partes de una narración?", ["Inicio, nudo y desenlace", "Título, autor y fecha", "Solo el final", "Ninguna",
      Q("¿Cuándo se declaró la independencia de Colombia?", ["1808", "1810", "1816", "1819"], "1810", "soc")
    ], "Inicio, nudo y desenlace", "leng"),
      Q("¿Qué palabras indican el orden de los sucesos? Ej: 'Primero, luego, finalmente'", ["Conectores temporales", "Sustantivos", "Colores", "Números"], "Conectores temporales", "leng"),
      Q("En el 'nudo' de una historia normalmente ocurre...", ["El problema o conflicto principal", "El final feliz", "La portada del libro", "Nada importante"], "El problema o conflicto principal", "leng"),
      Q("¿En qué parte de la narración se presenta el problema?", ["En el nudo", "En el inicio", "En el desenlace", "En el título"], "En el nudo", "leng"),
      Q("¿Cuál palabra conecta ideas en el tiempo?", ["Después", "Caballo", "Rápido", "Establo"], "Después", "leng"),
      Q("¿Qué debe tener el desenlace de una historia?", ["La solución o el final", "El comienzo del problema", "Solo personajes nuevos", "Nada especial"], "La solución o el final", "leng"),
    ],
    englishVocab: [
      { w: "First", es: "Primero", e: "1️⃣" },
      { w: "Then", es: "Luego", e: "➡️" },
      { w: "Finally", es: "Finalmente", e: "🏁" },
      { w: "Competition", es: "Competencia", e: "🏆" },
      { w: "Beginning", es: "Inicio", e: "🌱" },
      { w: "Problem", es: "Problema", e: "❓" },
      { w: "Ending", es: "Final", e: "🔚" },
      { w: "Feeling", es: "Sentimiento", e: "💗" },
    ],
    frenchVocab: [
      { w: "D'abord", es: "Primero", e: "1️⃣" },
      { w: "Ensuite", es: "Luego", e: "➡️" },
      { w: "Enfin", es: "Finalmente", e: "🏁" },
      { w: "Compétition", es: "Competencia", e: "🏆" },
      { w: "Début", es: "Inicio", e: "🌱" },
      { w: "Problème", es: "Problema", e: "❓" },
      { w: "Fin", es: "Final", e: "🔚" },
      { w: "Sentiment", es: "Sentimiento", e: "💗" },
    ],
    englishDialogue: [
      { t: "First, we warm up. Then, we compete!", es: "Primero calentamos. ¡Luego competimos!" },
      { t: "Finally, we celebrate!", es: "¡Finalmente celebramos!" },
      { t: "How does your story begin?", es: "¿Cómo empieza tu historia?" },
      { t: "With a big problem to solve!", es: "¡Con un gran problema por resolver!" },
    ],
    frenchDialogue: [
      { t: "D'abord, on s'échauffe. Ensuite, on participe!", es: "Primero calentamos. ¡Luego competimos!" },
      { t: "Enfin, on célèbre!", es: "¡Finalmente celebramos!" },
      { t: "Comment ton histoire commence-t-elle?", es: "¿Cómo empieza tu historia?" },
      { t: "Avec un grand problème à résoudre!", es: "¡Con un gran problema por resolver!" },
    ],
    journalPrompt: "Escribe la historia de 'Mi primera competencia' con inicio, nudo y desenlace, usando primero, luego y finalmente. Mínimo 6 líneas.",
  },
  {
    date: "Miércoles 22 de julio", title: "Razas de caballos", subjectLabel: "Ciencias Naturales",
    intro: "No todos los caballos son iguales. Aprendamos a clasificarlos por sus características.",
    isShowDay: false,
    subjectQuestions: [
      Q("Clasificar seres vivos según sus características se llama...", ["Clasificación", "Alimentación", "Migración", "Extinción"], "Clasificación", "cien"),
      Q("El caballo de paso fino es conocido por...", ["Su caminado suave y elegante", "Volar", "Nadar rápido", "Cambiar de color"], "Su caminado suave y elegante", "cien"),
      Q("¿Qué característica NO sirve para clasificar razas de caballos?", ["El color favorito de su dueño", "El tamaño", "El color del pelaje", "El tipo de andar"], "El color favorito de su dueño", "cien"),
      Q("¿Qué es una raza?", ["Un grupo de animales con características similares heredadas", "Un color solamente", "Un país", "Una comida"], "Un grupo de animales con características similares heredadas", "cien"),
      Q("¿Qué característica NO es física?", ["El nombre que le puso su dueño", "El tamaño", "El color del pelaje", "La forma de las orejas"], "El nombre que le puso su dueño", "cien"),
      Q("¿Qué caballo es conocido por ser muy veloz en carreras?", ["El pura sangre (thoroughbred)", "El de paso fino", "El poni", "Ninguno"], "El pura sangre (thoroughbred)", "cien"),
    ],
    englishVocab: [
      { w: "Breed", es: "Raza", e: "🐎" },
      { w: "Gallop", es: "Galopar", e: "💨" },
      { w: "Canter", es: "Medio galope", e: "🏃" },
      { w: "Trot", es: "Trotar", e: "🚶" },
      { w: "Speed", es: "Velocidad", e: "⚡" },
      { w: "Strong", es: "Fuerte", e: "💪" },
      { w: "Coat (fur)", es: "Pelaje", e: "🐴" },
      { w: "Tall", es: "Alto", e: "📏" },
    ],
    frenchVocab: [
      { w: "Race", es: "Raza", e: "🐎" },
      { w: "Galoper", es: "Galopar", e: "💨" },
      { w: "Petit galop", es: "Medio galope", e: "🏃" },
      { w: "Aller au trot", es: "Trotar", e: "🚶" },
      { w: "Vitesse", es: "Velocidad", e: "⚡" },
      { w: "Fort", es: "Fuerte", e: "💪" },
      { w: "Pelage", es: "Pelaje", e: "🐴" },
      { w: "Grand", es: "Alto", e: "📏" },
    ],
    englishDialogue: [
      { t: "Look, the horse is galloping!", es: "¡Mira, el caballo está galopando!" },
      { t: "Wow, that's so fast!", es: "¡Vaya, qué rápido!" },
      { t: "This breed has great speed.", es: "Esta raza tiene gran velocidad." },
      { t: "And a beautiful shiny coat!", es: "¡Y un pelaje brillante hermoso!" },
    ],
    frenchDialogue: [
      { t: "Regarde, le cheval galope!", es: "¡Mira, el caballo está galopando!" },
      { t: "Wahou, comme c'est rapide!", es: "¡Vaya, qué rápido!" },
      { t: "Cette race a une grande vitesse.", es: "Esta raza tiene gran velocidad." },
      { t: "Et un beau pelage brillant!", es: "¡Y un pelaje brillante hermoso!" },
    ],
    journalPrompt: "Describe (o inventa) una raza de caballo y sus principales características: tamaño, color, velocidad y para qué se usa.",
  },
  {
    date: "Jueves 23 de julio", title: "Deportes ecuestres del mundo", subjectLabel: "Ciencias Sociales",
    intro: "El caballo se monta en todo el mundo. Conozcamos algunos deportes ecuestres.",
    isShowDay: false,
    subjectQuestions: [
      Q("El polo es un deporte ecuestre popular en países como...", ["Argentina e Inglaterra", "Solo en Colombia", "Solo en Asia", "En ningún lugar",
      Q("¿Quién fue Simón Bolívar?", ["Libertador de varios países de América", "Rey de España", "Cazador de caballos", "Inventor"], "Libertador de varios países de América", "soc")
    ], "Argentina e Inglaterra", "soc"),
      Q("El 'dressage' o doma clásica es un deporte ecuestre de origen...", ["Francés/Europeo", "Africano", "Solo colombiano", "Ninguno"], "Francés/Europeo", "soc"),
      Q("¿Qué valor es importante en los deportes ecuestres?", ["El respeto y cuidado por el animal", "Ganar a cualquier costo", "La velocidad del carro", "Ninguno"], "El respeto y cuidado por el animal", "soc"),
      Q("¿Qué deporte ecuestre se juega en equipo con un mazo y una bola?", ["Polo", "Doma clásica", "Salto", "Ninguno"], "Polo", "soc"),
      Q("¿Qué valor NO debería faltar en los deportes ecuestres?", ["El respeto por el animal", "La velocidad extrema sin cuidado", "El maltrato", "Ninguno de los anteriores"], "El respeto por el animal", "soc"),
      Q("¿En qué continente se originó gran parte de la equitación clásica moderna?", ["Europa", "Oceanía", "Antártida", "Ninguno"], "Europa", "soc"),
    ],
    englishVocab: [
      { w: "Sport", es: "Deporte", e: "🏅" },
      { w: "Competition", es: "Competencia", e: "🏆" },
      { w: "Rider", es: "Jinete", e: "🏇" },
      { w: "Country", es: "País", e: "🌍" },
      { w: "Team", es: "Equipo", e: "👥" },
      { w: "Rules", es: "Reglas", e: "📋" },
      { w: "Respect", es: "Respeto", e: "🙏" },
      { w: "Culture", es: "Cultura", e: "🎭" },
    ],
    frenchVocab: [
      { w: "Sport", es: "Deporte", e: "🏅" },
      { w: "Compétition", es: "Competencia", e: "🏆" },
      { w: "Cavalier", es: "Jinete", e: "🏇" },
      { w: "Pays", es: "País", e: "🌍" },
      { w: "Équipe", es: "Equipo", e: "👥" },
      { w: "Règles", es: "Reglas", e: "📋" },
      { w: "Respect", es: "Respeto", e: "🙏" },
      { w: "Culture", es: "Cultura", e: "🎭" },
    ],
    englishDialogue: [
      { t: "Which equestrian sport do you like?", es: "¿Qué deporte ecuestre te gusta?" },
      { t: "I love show jumping!", es: "¡Me encanta el salto de obstáculos!" },
      { t: "Every sport needs rules.", es: "Todo deporte necesita reglas." },
      { t: "And respect for the horse always.", es: "Y respeto por el caballo siempre." },
    ],
    frenchDialogue: [
      { t: "Quel sport équestre aimes-tu?", es: "¿Qué deporte ecuestre te gusta?" },
      { t: "J'adore le saut d'obstacles!", es: "¡Me encanta el salto de obstáculos!" },
      { t: "Chaque sport a besoin de règles.", es: "Todo deporte necesita reglas." },
      { t: "Et du respect pour le cheval toujours.", es: "Y respeto por el caballo siempre." },
    ],
    journalPrompt: "¿Qué deporte ecuestre te gustaría practicar? Explica por qué, y qué reglas o valores importantes tiene ese deporte.",
  },
  {
    date: "Viernes 24 de julio", title: "Concurso Hípico #3", subjectLabel: "Simulación de competencia", isShowDay: true,
    intro: "¡El concurso más difícil hasta ahora! Simulemos una competencia real con puntaje.",
    subjectQuestions: [
      Q("El puntaje inicia en 100 y se restan 5 por cada obstáculo derribado. Si derribaste 2, ¿cuál es tu puntaje?", ["95", "90", "85", "80"], "90", "mate"),
      Q("Ordena la secuencia de una competencia: Calentamiento, Competencia, Premiación. ¿Qué va primero?", ["Calentamiento", "Competencia", "Premiación", "Ninguna"], "Calentamiento", "leng"),
      Q("¿Qué país asocias con la tradición del caballo de paso fino?", ["Colombia", "Rusia", "Egipto", "Canadá"], "Colombia", "soc"),
      Q("Si tu puntaje inicial es 100 y pierdes 5 puntos por cada error, con 3 errores ¿cuál es tu puntaje?", ["80", "85", "90", "95"], "85", "mate"),
      Q("¿Cuál palabra describe cómo se sintió el jinete? 'El jinete estaba nervioso pero feliz'", ["Nervioso y feliz", "Enojado", "Aburrido", "Cansado"], "Nervioso y feliz", "leng"),
      Q("¿Qué representa una medalla de oro en una competencia?", ["El primer lugar", "El último lugar", "Ninguna posición", "Un error"], "El primer lugar", "soc"),
    ],
    englishVocab: [
      { w: "Score", es: "Puntaje", e: "📊" },
      { w: "Warm-up", es: "Calentamiento", e: "🔥" },
      { w: "Medal", es: "Medalla", e: "🥇" },
      { w: "Winner", es: "Ganador", e: "🏆" },
      { w: "Nervous", es: "Nervioso(a)", e: "😬" },
      { w: "Proud", es: "Orgulloso(a)", e: "🥰" },
      { w: "Effort", es: "Esfuerzo", e: "💪" },
      { w: "Result", es: "Resultado", e: "📈" },
    ],
    frenchVocab: [
      { w: "Score", es: "Puntaje", e: "📊" },
      { w: "Échauffement", es: "Calentamiento", e: "🔥" },
      { w: "Médaille", es: "Medalla", e: "🥇" },
      { w: "Gagnant", es: "Ganador", e: "🏆" },
      { w: "Nerveux/Nerveuse", es: "Nervioso(a)", e: "😬" },
      { w: "Fier/Fière", es: "Orgulloso(a)", e: "🥰" },
      { w: "Effort", es: "Esfuerzo", e: "💪" },
      { w: "Résultat", es: "Resultado", e: "📈" },
    ],
    englishDialogue: [
      { t: "And she jumps! Great time!", es: "¡Y ella salta! ¡Excelente tiempo!" },
      { t: "She wins the gold medal!", es: "¡Ella gana la medalla de oro!" },
      { t: "I feel nervous but ready.", es: "Me siento nerviosa pero lista." },
      { t: "Your effort will show in the result!", es: "¡Tu esfuerzo se verá en el resultado!" },
    ],
    frenchDialogue: [
      { t: "Et elle saute! Quel bon temps!", es: "¡Y ella salta! ¡Excelente tiempo!" },
      { t: "Elle gagne la médaille d'or!", es: "¡Ella gana la medalla de oro!" },
      { t: "Je me sens nerveuse mais prête.", es: "Me siento nerviosa pero lista." },
      { t: "Ton effort se verra dans le résultat!", es: "¡Tu esfuerzo se verá en el resultado!" },
    ],
    journalPrompt: "Describe cómo te sentiste en tu simulación de competencia de hoy, desde el calentamiento hasta el resultado final.",
  },

  // ---------------- SEMANA 5 ----------------
  {
    date: "Lunes 27 de julio", title: "Repaso final: Matemáticas", subjectLabel: "Matemáticas",
    intro: "Última semana antes del Gran Concurso. ¡Repasemos todo lo aprendido en matemáticas!",
    isShowDay: false,
    subjectQuestions: [
      Q("Un caballo recorre 5 km por hora. ¿Cuántos km recorre en 3 horas?", ["10", "15", "20", "8",
      Q("¿En qué año se formó la República de la Gran Colombia?", ["1800", "1819", "1830", "1850"], "1819", "soc")
    ], "15", "mate"),
      Q("¿Cuál es el perímetro de un corral cuadrado de lado 4 m?", ["8", "12", "16", "20"], "16", "mate"),
      Q("3/4 + 1/4 = ?", ["1 (un entero)", "4/8", "2/4", "0"], "1 (un entero)", "mate"),
      Q("¿Cuánto es 9 x 7?", ["56", "63", "72", "54"], "63", "mate"),
      Q("Un corral rectangular mide 8 m de largo y 5 m de ancho. ¿Cuál es su perímetro?", ["13 m", "18 m", "26 m", "40 m"], "26 m", "mate"),
      Q("¿Cuánto es 100 ÷ 4?", ["20", "25", "30", "4"], "25", "mate"),
    ],
    englishVocab: [
      { w: "Distance", es: "Distancia", e: "📏" },
      { w: "Hour", es: "Hora", e: "🕐" },
      { w: "Fraction", es: "Fracción", e: "🍰" },
      { w: "Perimeter", es: "Perímetro", e: "🔲" },
      { w: "Multiply", es: "Multiplicar", e: "✖️" },
      { w: "Divide", es: "Dividir", e: "➗" },
      { w: "Total", es: "Total", e: "🧮" },
      { w: "Number", es: "Número", e: "🔢" },
    ],
    frenchVocab: [
      { w: "Distance", es: "Distancia", e: "📏" },
      { w: "Heure", es: "Hora", e: "🕐" },
      { w: "Fraction", es: "Fracción", e: "🍰" },
      { w: "Périmètre", es: "Perímetro", e: "🔲" },
      { w: "Multiplier", es: "Multiplicar", e: "✖️" },
      { w: "Diviser", es: "Dividir", e: "➗" },
      { w: "Total", es: "Total", e: "🧮" },
      { w: "Nombre", es: "Número", e: "🔢" },
    ],
    englishDialogue: [
      { t: "How far did we ride today?", es: "¿Qué distancia cabalgamos hoy?" },
      { t: "Fifteen kilometers in three hours!", es: "¡Quince kilómetros en tres horas!" },
      { t: "Let's multiply the numbers.", es: "Multipliquemos los números." },
      { t: "Great, now we have the total!", es: "¡Genial, ya tenemos el total!" },
    ],
    frenchDialogue: [
      { t: "Quelle distance avons-nous parcourue?", es: "¿Qué distancia recorrimos?" },
      { t: "Quinze kilomètres en trois heures!", es: "¡Quince kilómetros en tres horas!" },
      { t: "Multiplions les nombres.", es: "Multipliquemos los números." },
      { t: "Super, maintenant nous avons le total!", es: "¡Genial, ya tenemos el total!" },
    ],
    journalPrompt: "Escribe 5 cosas de matemáticas que aprendiste este mes en el rancho, con un ejemplo de cada una.",
  },
  {
    date: "Martes 28 de julio", title: "Repaso final: Lenguaje", subjectLabel: "Lenguaje",
    intro: "Vamos a escribir la crónica de todo el verano de Miranda en el rancho.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Qué tipo de texto usarías para contar tu verano en el rancho?", ["Narrativo", "Instructivo", "Solo números", "Ninguno"], "Narrativo", "leng"),
      Q("¿Cuál es un sinónimo de 'feliz'?", ["Contento", "Triste", "Enojado", "Cansado"], "Contento", "leng"),
      Q("¿Qué signo se usa al inicio y al final de una pregunta en español?", ["¿ y ?", ". y ,", ", y ;", "Ninguno"], "¿ y ?", "leng"),
      Q("¿Qué es una crónica?", ["Un relato de hechos en orden de tiempo", "Una poesía sin sentido", "Un número", "Un dibujo"], "Un relato de hechos en orden de tiempo", "leng"),
      Q("¿Cuál oración usa signos de interrogación correctamente?", ["¿Cómo estás?", "Como estas?", "¿Como estas", "Cómo estás?."], "¿Cómo estás?", "leng"),
      Q("¿Cuál es el antónimo de 'feliz'?", ["Triste", "Contento", "Alegre", "Sonriente"], "Triste", "leng"),
    ],
    englishVocab: [
      { w: "Summer", es: "Verano", e: "☀️" },
      { w: "Chronicle", es: "Crónica", e: "📰" },
      { w: "Happy", es: "Feliz", e: "😄" },
      { w: "Adventure", es: "Aventura", e: "🗺️" },
      { w: "Question", es: "Pregunta", e: "❓" },
      { w: "Answer", es: "Respuesta", e: "💬" },
      { w: "Memory", es: "Recuerdo", e: "🧠" },
      { w: "Learn", es: "Aprender", e: "🎓" },
    ],
    frenchVocab: [
      { w: "Été", es: "Verano", e: "☀️" },
      { w: "Chronique", es: "Crónica", e: "📰" },
      { w: "Heureux/Heureuse", es: "Feliz", e: "😄" },
      { w: "Aventure", es: "Aventura", e: "🗺️" },
      { w: "Question", es: "Pregunta", e: "❓" },
      { w: "Réponse", es: "Respuesta", e: "💬" },
      { w: "Souvenir", es: "Recuerdo", e: "🧠" },
      { w: "Apprendre", es: "Aprender", e: "🎓" },
    ],
    englishDialogue: [
      { t: "How was your summer?", es: "¿Cómo fue tu verano?" },
      { t: "It was a wonderful adventure!", es: "¡Fue una aventura maravillosa!" },
      { t: "What is your favorite memory?", es: "¿Cuál es tu recuerdo favorito?" },
      { t: "Riding Luna for the first time!", es: "¡Montar a Luna por primera vez!" },
    ],
    frenchDialogue: [
      { t: "Comment était ton été?", es: "¿Cómo fue tu verano?" },
      { t: "C'était une aventure merveilleuse!", es: "¡Fue una aventura maravillosa!" },
      { t: "Quel est ton souvenir préféré?", es: "¿Cuál es tu recuerdo favorito?" },
      { t: "Monter Luna pour la première fois!", es: "¡Montar a Luna por primera vez!" },
    ],
    journalPrompt: "Escribe la crónica de tu verano en el rancho, en orden: cómo empezó, qué aprendiste, y cómo te sientes ahora (mínimo 7 líneas).",
  },
  {
    date: "Miércoles 29 de julio", title: "Repaso final: Ciencias Naturales", subjectLabel: "Ciencias Naturales",
    intro: "Creemos un afiche con todo lo que aprendimos sobre el cuidado de los caballos.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Qué necesita un caballo para estar sano?", ["Agua, alimento y cuidado", "Solo agua", "Solo compañía", "Nada",
      Q("¿Qué son las cordilleras?", ["Cadenas de montañas", "Ríos grandes", "Océanos", "Ciudades"], "Cadenas de montañas", "soc")
    ], "Agua, alimento y cuidado", "cien"),
      Q("¿Qué parte del cuerpo usa el caballo para caminar?", ["Las patas y cascos", "Las orejas", "Los ojos", "La cola"], "Las patas y cascos", "cien"),
      Q("El agua de lluvia llega al bebedero gracias a...", ["El ciclo del agua", "La magia", "El viento solo", "Nada"], "El ciclo del agua", "cien"),
      Q("¿Qué grupo de seres vivos NO puede fabricar su propio alimento?", ["Los animales", "Las plantas", "Ambos pueden", "Ninguno"], "Los animales", "cien"),
      Q("¿Qué es un hábitat?", ["El lugar donde vive un ser vivo", "Un tipo de comida", "Un color", "Un número"], "El lugar donde vive un ser vivo", "cien"),
      Q("¿Por qué el ejercicio es bueno para los caballos?", ["Fortalece sus músculos y huesos", "No sirve para nada", "Los hace más lentos", "Los enferma"], "Fortalece sus músculos y huesos", "cien"),
    ],
    englishVocab: [
      { w: "Healthy", es: "Sano", e: "💪" },
      { w: "Care", es: "Cuidado", e: "❤️" },
      { w: "Poster", es: "Afiche", e: "🖼️" },
      { w: "Body", es: "Cuerpo", e: "🐴" },
      { w: "Habitat", es: "Hábitat", e: "🏞️" },
      { w: "Exercise", es: "Ejercicio", e: "🏃" },
      { w: "Nature", es: "Naturaleza", e: "🌿" },
      { w: "Living being", es: "Ser vivo", e: "🌍" },
    ],
    frenchVocab: [
      { w: "En bonne santé", es: "Sano", e: "💪" },
      { w: "Soin", es: "Cuidado", e: "❤️" },
      { w: "Affiche", es: "Afiche", e: "🖼️" },
      { w: "Corps", es: "Cuerpo", e: "🐴" },
      { w: "Habitat", es: "Hábitat", e: "🏞️" },
      { w: "Exercice", es: "Ejercicio", e: "🏃" },
      { w: "Nature", es: "Naturaleza", e: "🌿" },
      { w: "Être vivant", es: "Ser vivo", e: "🌍" },
    ],
    englishDialogue: [
      { t: "How do we keep the horse healthy?", es: "¿Cómo mantenemos sano al caballo?" },
      { t: "With water, food and lots of care!", es: "¡Con agua, comida y mucho cuidado!" },
      { t: "Horses need daily exercise.", es: "Los caballos necesitan ejercicio diario." },
      { t: "Just like us, to stay healthy!", es: "¡Igual que nosotros, para estar sanos!" },
    ],
    frenchDialogue: [
      { t: "Comment garder le cheval en bonne santé?", es: "¿Cómo mantenemos sano al caballo?" },
      { t: "Avec de l'eau, de la nourriture et des soins!", es: "¡Con agua, comida y cuidados!" },
      { t: "Les chevaux ont besoin d'exercice quotidien.", es: "Los caballos necesitan ejercicio diario." },
      { t: "Comme nous, pour rester en bonne santé!", es: "¡Igual que nosotros, para estar sanos!" },
    ],
    journalPrompt: "Describe con palabras un afiche sobre el cuidado integral de un caballo: qué dibujos tendría y qué consejos daría.",
  },
  {
    date: "Jueves 30 de julio", title: "Repaso final: Ciencias Sociales", subjectLabel: "Ciencias Sociales",
    intro: "Presentemos el rancho completo: su mapa, su gente y su cultura.",
    isShowDay: false,
    subjectQuestions: [
      Q("¿Qué región de Colombia es famosa por la ganadería y los llanos?", ["Los Llanos Orientales", "La Amazonía profunda", "El desierto", "Ninguna"], "Los Llanos Orientales", "soc"),
      Q("Un mapa nos ayuda a...", ["Ubicarnos y encontrar rutas", "Cocinar", "Dormir", "Nada"], "Ubicarnos y encontrar rutas", "soc"),
      Q("El polo y el dressage son ejemplos de...", ["Deportes ecuestres", "Comidas típicas", "Animales", "Instrumentos"], "Deportes ecuestres", "soc"),
      Q("¿Qué es la cultura de un lugar?", ["Sus costumbres, comida, música y tradiciones", "Solo su clima", "Solo su idioma", "Nada"], "Sus costumbres, comida, música y tradiciones", "soc"),
      Q("¿Qué región colombiana es reconocida por el café?", ["La región Andina/Cafetera", "El desierto", "La Amazonía", "El mar Caribe únicamente"], "La región Andina/Cafetera", "soc"),
      Q("¿Qué significa 'diversidad cultural'?", ["Que existen muchas culturas diferentes conviviendo", "Que solo hay una cultura", "Que no hay reglas", "Ninguna"], "Que existen muchas culturas diferentes conviviendo", "soc"),
    ],
    englishVocab: [
      { w: "Region", es: "Región", e: "🗺️" },
      { w: "Culture", es: "Cultura", e: "🎭" },
      { w: "World", es: "Mundo", e: "🌎" },
      { w: "Tradition", es: "Tradición", e: "🎉" },
      { w: "Diverse", es: "Diverso(a)", e: "🌈" },
      { w: "Community", es: "Comunidad", e: "🏘️" },
      { w: "Celebrate", es: "Celebrar", e: "🎊" },
      { w: "Proud", es: "Orgulloso(a)", e: "🥰" },
    ],
    frenchVocab: [
      { w: "Région", es: "Región", e: "🗺️" },
      { w: "Culture", es: "Cultura", e: "🎭" },
      { w: "Monde", es: "Mundo", e: "🌎" },
      { w: "Tradition", es: "Tradición", e: "🎉" },
      { w: "Divers(e)", es: "Diverso(a)", e: "🌈" },
      { w: "Communauté", es: "Comunidad", e: "🏘️" },
      { w: "Célébrer", es: "Celebrar", e: "🎊" },
      { w: "Fier/Fière", es: "Orgulloso(a)", e: "🥰" },
    ],
    englishDialogue: [
      { t: "Tell me about your ranch.", es: "Cuéntame sobre tu rancho." },
      { t: "It has a map, a river and lots of tradition!", es: "¡Tiene un mapa, un río y mucha tradición!" },
      { t: "Our ranch community is diverse.", es: "Nuestra comunidad del rancho es diversa." },
      { t: "Let's celebrate all our traditions!", es: "¡Celebremos todas nuestras tradiciones!" },
    ],
    frenchDialogue: [
      { t: "Parle-moi de ton ranch.", es: "Cuéntame sobre tu rancho." },
      { t: "Il a une carte, une rivière et beaucoup de tradition!", es: "¡Tiene un mapa, un río y mucha tradición!" },
      { t: "Notre communauté du ranch est diverse.", es: "Nuestra comunidad del rancho es diversa." },
      { t: "Célébrons toutes nos traditions!", es: "¡Celebremos todas nuestras tradiciones!" },
    ],
    journalPrompt: "Presenta (por escrito) el rancho completo: su mapa, su gente, sus oficios y su cultura. Mínimo 7 líneas.",
  },
  {
    date: "Viernes 31 de julio", title: "🏆 Gran Concurso de Verano", subjectLabel: "Evento final", isShowDay: true, isFinal: true,
    intro: "¡Es el gran día! Miranda compite en el Gran Concurso de Verano usando todo lo aprendido en julio.",
    subjectQuestions: [
      Q("Un corral mide 6 m x 4 m. ¿Cuál es su área?", ["24", "20", "10", "28",
      Q("¿Cuántas cordilleras principales tiene Colombia?", ["2", "3", "4", "5"], "3", "soc")
    ], "24", "mate"),
      Q("¿Cuál es la moraleja típica de las fábulas?", ["Enseñar un valor o lección", "Dar risa nada más", "No tiene sentido", "Ninguna"], "Enseñar un valor o lección", "leng"),
      Q("¿Qué necesita todo ser vivo para vivir?", ["Agua, alimento y aire", "Solo dinero", "Nada", "Solo juguetes"], "Agua, alimento y aire", "cien"),
      Q("¿Qué representan los puntos cardinales en un mapa?", ["Las direcciones norte, sur, este y oeste", "Los colores", "Los números", "Nada"], "Las direcciones norte, sur, este y oeste", "soc"),
      Q("Un circuito de 100 m se divide en 4 partes iguales. ¿Cuánto mide cada parte?", ["20 m", "25 m", "30 m", "50 m"], "25 m", "mate"),
      Q("¿Qué debe tener una buena crónica del verano?", ["Orden de los hechos y detalles interesantes", "Solo números", "Nada especial", "Solo dibujos"], "Orden de los hechos y detalles interesantes", "leng"),
      Q("¿Qué aprendiste sobre el cuidado de los caballos este verano?", ["Necesitan agua, comida, ejercicio y cariño", "No necesitan cuidado", "Solo necesitan agua", "Ninguna de las anteriores"], "Necesitan agua, comida, ejercicio y cariño", "cien"),
      Q("¿Qué representa ganar el Gran Concurso de Verano?", ["El esfuerzo y aprendizaje de todo el mes", "Solo suerte", "Nada importante", "Un error"], "El esfuerzo y aprendizaje de todo el mes", "soc"),
    ],
    englishVocab: [
      { w: "Grand Prix", es: "Gran Premio", e: "🏆" },
      { w: "Champion", es: "Campeona", e: "👑" },
      { w: "Congratulations", es: "Felicitaciones", e: "🎉" },
      { w: "Proud", es: "Orgullosa", e: "🥰" },
      { w: "Journey", es: "Recorrido/Viaje", e: "🛤️" },
      { w: "Achievement", es: "Logro", e: "🏅" },
      { w: "Together", es: "Juntas(os)", e: "🤝" },
      { w: "Forever", es: "Para siempre", e: "♾️" },
    ],
    frenchVocab: [
      { w: "Grand Prix", es: "Gran Premio", e: "🏆" },
      { w: "Championne", es: "Campeona", e: "👑" },
      { w: "Félicitations", es: "Felicitaciones", e: "🎉" },
      { w: "Fière", es: "Orgullosa", e: "🥰" },
      { w: "Parcours", es: "Recorrido/Viaje", e: "🛤️" },
      { w: "Réussite", es: "Logro", e: "🏅" },
      { w: "Ensemble", es: "Juntas(os)", e: "🤝" },
      { w: "Pour toujours", es: "Para siempre", e: "♾️" },
    ],
    englishDialogue: [
      { t: "Welcome to the Summer Grand Prix!", es: "¡Bienvenidos al Gran Premio de Verano!" },
      { t: "Miranda is ready to jump!", es: "¡Miranda está lista para saltar!" },
      { t: "And she wins the gold medal! Congratulations!", es: "¡Y gana la medalla de oro! ¡Felicitaciones!" },
      { t: "What an amazing journey this summer!", es: "¡Qué recorrido tan increíble este verano!" },
      { t: "We did it together, forever friends!", es: "¡Lo logramos juntas, amigas para siempre!" },
    ],
    frenchDialogue: [
      { t: "Bienvenue au Grand Prix d'été!", es: "¡Bienvenidos al Gran Premio de Verano!" },
      { t: "Miranda est prête à sauter!", es: "¡Miranda está lista para saltar!" },
      { t: "Et elle gagne la médaille d'or! Félicitations!", es: "¡Y gana la medalla de oro! ¡Felicitaciones!" },
      { t: "Quel parcours incroyable cet été!", es: "¡Qué recorrido tan increíble este verano!" },
      { t: "On l'a fait ensemble, amies pour toujours!", es: "¡Lo logramos juntas, amigas para siempre!" },
    ],
    journalPrompt: "Escribe una carta a tu caballo agradeciéndole por este verano de aprendizaje. Cuéntale qué aprendiste y qué recordarás siempre (mínimo 8 líneas).",
  },
];

// Insignias por materia/idioma (umbral calculado en runtime como 70% del total disponible)
const BADGES = [
  { id: "mate", name: "Jinete Matemático", cat: "mate", emoji: "🐎" },
  { id: "leng", name: "Pluma de Oro", cat: "leng", emoji: "🪶" },
  { id: "cien", name: "Guardián de la Naturaleza", cat: "cien", emoji: "🌿" },
  { id: "soc", name: "Explorador del Rancho", cat: "soc", emoji: "🧭" },
  { id: "en", name: "English Trailblazer", cat: "en", emoji: "🏇" },
  { id: "fr", name: "Étoile du Français", cat: "fr", emoji: "🎪" },
];
